Repository encode/starlette, pull requests merged in 2022-05, with the labels that each got.

#1620 Skip test when brotli is installed
  tests/test_requests.py
  tests/test_websockets.py
Labels: clean up

#1625 Secret: add a __bool__ implementation
  starlette/datastructures.py
  tests/test_config.py
Labels: feature

#1609 Do not send empty data to `StreamingResponse` on `BaseHTTPMiddleware`
  starlette/middleware/base.py
Labels: bug

#1636 Document `status_code` parameter on `requires` when using WebSockets
  docs/authentication.md
Labels: documentation, websocket

#1638 Add third party package Startlette-Login
  docs/third-party-packages.md
Labels: documentation

#1640 Document `BaseHTTPMiddleware` bugs
  docs/middleware.md
Labels: documentation

#1444 Improve detection of async callables
  starlette/_utils.py
  starlette/authentication.py
  starlette/background.py
  starlette/endpoints.py
  starlette/middleware/errors.py
  starlette/middleware/exceptions.py
  starlette/routing.py
  starlette/testclient.py
  tests/test__utils.py
Labels: bug, refactor

#1377 Allow staticfiles to follow symlinks outside directory
  starlette/staticfiles.py
  tests/test_staticfiles.py
Labels: bug, staticfiles
