Repository encode/starlette, pull requests merged in 2022-02, with the labels that each got.

#1349 Raise KeyError at early stage for missing boundary
  starlette/formparsers.py
  tests/test_formparsers.py
Labels: feature, refactor

#1477 Docs refresh
  README.md
  docs/index.md
Labels: documentation

#1378 Add overload in Config.__call__ for cast as Callable
  starlette/config.py
  tests/test_config.py
Labels: feature

#1480 Update document about jinja2 custom filters link
  docs/templates.md
Labels: documentation

#1460 Bump anyio requirement from 3.x to 3.x, 4.x
  setup.py
Labels: maintenance

#1489 Remove routing decorators in `test_application.py`
  starlette/applications.py
  starlette/routing.py
  tests/test_applications.py
Labels: clean up

#1507 Switch to a discussion-first workflow
  .github/ISSUE_TEMPLATE/1-issue.md
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
Labels: maintenance

#1504 Deprecate `WSGIMiddleware` in favor of `a2wsgi`
  docs/middleware.md
  setup.cfg
  starlette/middleware/wsgi.py
Labels: clean up

#1512 SessionMiddleware uses an explicit path=..., instead of defaulting to the ASGI 'root_path'.
  starlette/middleware/sessions.py
  tests/middleware/test_session.py
Labels: bug

#1443 Deprecate `concurrency.run_until_first_complete`
  setup.cfg
  starlette/concurrency.py
Labels: clean up

#1363 Display missing route details.
  starlette/routing.py
  tests/test_routing.py
Labels: feature

#1266 Add content disposition type parameter to FileResponse
  docs/responses.md
  starlette/responses.py
  tests/test_responses.py
Labels: feature

#1442 Add PR template
  .github/pull_request_template.md
Labels: maintenance

#1240 Add union operators to MutableHeaders
  starlette/datastructures.py
  tests/test_datastructures.py
Labels: feature

#920 Add `next` query param with original request URL in requires decorator
  docs/authentication.md
  starlette/authentication.py
  tests/test_authentication.py
Labels: feature, outdated
