Repository encode/starlette, pull requests merged in 2022-01, with the labels that each got.

#1388 Add `WebSocketRoute` docs in `Routing`
  docs/routing.md
Labels: documentation, websocket

#1353 Add Mypy checks to tests
  setup.cfg
  tests/middleware/test_cors.py
  tests/middleware/test_session.py
  tests/test_database.py
  tests/test_datastructures.py
  tests/test_formparsers.py
  tests/test_routing.py
  tests/test_templates.py
Labels: typing

#1412 Use typing `NoReturn`
  requirements.txt
  starlette/datastructures.py
  starlette/middleware/gzip.py
  starlette/requests.py
Labels: typing

#1421 Remove manual contextvar copy logic
  setup.py
  starlette/concurrency.py
  tests/test_concurrency.py
Labels: clean up
