Repository encode/starlette, pull requests merged in 2022-09, with the labels that each got.

#1263 Add `WebSocketException` and support for WS handlers
  docs/exceptions.md
  starlette/exceptions.py
  starlette/middleware/exceptions.py
  tests/test_applications.py
  tests/test_exceptions.py
Labels: feature, websocket

#1845 Remove reference to `DatabaseMiddleware` in the documentation
  docs/config.md
  docs/database.md
Labels: documentation

#1376 Replace HTTP client on TestClient from `requests` to `httpx`
  README.md
  docs/index.md
  docs/testclient.md
  pyproject.toml
  requirements.txt
  setup.cfg
  starlette/testclient.py
  tests/middleware/test_cors.py
  tests/middleware/test_session.py
  tests/test_formparsers.py
  tests/test_requests.py
  tests/test_responses.py
  tests/test_staticfiles.py
Labels: feature, clean up

#1649 Add Mount(..., middleware=[...])
  docs/middleware.md
  starlette/routing.py
  tests/test_routing.py
Labels: feature, hold
