Repository encode/starlette, pull requests merged in 2023-02, with the labels that each got.

#1683 Allow StaticFiles follow symlinks
  docs/staticfiles.md
  starlette/staticfiles.py
  tests/test_staticfiles.py
Labels: staticfiles

#1413 Make the file argument to UploadFile required
  starlette/datastructures.py
  starlette/formparsers.py
  tests/test_datastructures.py
Labels: refactor

#1405 Feature: Add size attribute to UploadFile
  docs/requests.md
  starlette/datastructures.py
  starlette/formparsers.py
  tests/test_datastructures.py
  tests/test_formparsers.py
Labels: feature

#2029 Document that UploadFile's `filename` and `content_type` can be `None`
  docs/requests.md
Labels: documentation
